### ISSUE TITLE
Possibility of merging extra features?

### ISSUE THREAD

**Issue by g-radam** [maxicarlos08/gphoto2-rs#1]
Hi! The creation of this repo / crate is very well timed. I actually forked gphoto2 myself a month or two to add extra functionality as [@dcuddeback](https://github.com/dcuddeback/)'s repos are dead.  Are we able to go over the code I wrote / possibly clean it up and get it merged??

**Edit** It looks like you have added most features! Great work! I have two requests below **Edit**
.
.

Below is a summary of my features:

Added in-memory file downloads: [add-in-memory-filemedia](https://github.com/g-radam/gphoto-rs/tree/add-in-memory-filemedia)
 - Added means to save a FileMedia into a memory buffer instead of a file. Code was taken from various forks of the original @dcuddeback.
 - ********* Looks like you added this in (More idiomatic I might add - using new's): https://github.com/maxicarlos08/gphoto2-rs/blob/6649fdb3387a6c3c5a31da5709fe9b378fc88fee/src/file.rs#L154 please ignore *********

Added ability to query and update widgets: [add-camera-widget](https://github.com/g-radam/gphoto-rs/tree/add-camera-widget)
 - Added "widget.rs". Logic was taken from gphoto2-cli app (where you set / get widgets)
 - Looks like you added this already (Much better than my code - more idiomatic).
 - ********* I have an extra function though to set the widgets value from a string - The logic was copied from gphoto2-cli. Would be nice to see this implemented. My code: https://github.com/g-radam/gphoto-rs/blob/9633bf5cf3696f3b1765fbcfae1f3debc0e152b7/src/widget.rs#L171 *********

Added ability to stream video out of device: [add-camera-video](https://github.com/g-radam/gphoto-rs/tree/add-camera-video)
 - Added "video.rs" - Logic was taken from gphoto2-cli app (where you can --stdout / fd out the cameras liveview for realtime 30fps video)
 - ********* This code is very much half-baked, but it simply asks gphoto2 to write frames to either the stdout fd, or a file fd. I've used this code and it works without issues. https://github.com/g-radam/gphoto-rs/blob/9633bf5cf3696f3b1765fbcfae1f3debc0e152b7/src/video.rs#L1 *********

Post edit: Since It looks like you have implemented most features I had (and your code better written than mine), there is no point integrating any of my code mentioned above. The only two potential requests I have are to implement the video streaming (video.rs), and the Widget::set_value_string function. That would make this crate 100% usable for my needs, and I can archive my github fork :) 

Thanks!

**Comment by maxicarlos08** [comment]
Hello @g-radam!

First of all thanks for reaching out and creating this issue!, but I'm afraid that I will have to disappoint you :/  
This project aims to implement all the features of libpghoto2, so that other projects can use this crate to create their own front-ends for libgphoto2. Implementing the features of the gphoto cli is not the point of this project.

To make your life a bit easier, here is an implementation of the `Widget::set_value_string` function:

```rust
use gphoto2::{
    widget::{Widget, WidgetType, WidgetValue},
    Result,
};

pub fn widget_set_value_text(widget: &mut Widget, value: String) -> Result<()> {
    match widget.widget_type()? {
        WidgetType::Window | WidgetType::Section | WidgetType::Button => {
            Err("Cannot set value to this widget type")?
        }
        WidgetType::Text => {
            widget.set_value(WidgetValue::Text(value))?;
        }
        WidgetType::Toggle => {
            let toggled = match value.as_str() {
                "on" | "yes" | "true" | "1" => true,
                _ => false,
            };

            widget.set_value(WidgetValue::Toggle(toggled))?;
        }
        WidgetType::Menu { choices, .. } => {
            if choices.contains(&value) {
                widget.set_value(WidgetValue::Menu(value))?;
            } else if let Ok(choice_i) = value.parse::<usize>() {
                if choice_i < choices.len() {
                    widget.set_value(WidgetValue::Menu(choices[choice_i].to_owned()))?;
                } else {
                    Err("Choice index is too large")?
                }
            } else {
                Err("Invalid value for choices")?
            }
        }
        WidgetType::Range { min, max, .. } => {
            if let Ok(range_value) = value.parse::<f32>() {
                if (min..=max).contains(&range_value) {
                    widget.set_value(WidgetValue::Range(range_value))?;
                } else {
                    Err("Range value out of range")?
                }
            } else {
                Err("Range value must be a number")?
            }
        }
        WidgetType::Date => {
            if let Ok(unix_timestamp) = value.parse::<i32>() {
                widget.set_value(WidgetValue::Date(unix_timestamp))?;
            } else {
                Err("Date must be an unix timestamp")?
            }
        }
    }

    // And then set the widget to the camera using `camera.set_config()`

    Ok(())
}
```
In the next release I'm adding two traits (Inner and InnerPtr) which allow you to interact with the inner libgphoto2 pointers. This should allow your to also implement the Video recording stuff.

I hope you understand me! (And sorry for the late response)

**Comment by g-radam** [comment]
Hi @maxicarlos08 I appreciate you getting back to me! By no means did I want to integrate too abstract gphoto2-cli features into this code base (I was just using it as a reference), however based on the code I was working with it seemed somewhat half rational-ish to implement the above set-wiget-from-string / polling of the liveview.

To elaborate, the core of the issue is/was not having access to the inner data (widget type enums / libgphoto PTR's) - I assumed the intention was to *not* expose internal C ptr's / enums based on @dcuddeback's code. However It looks like you did in fact expose the widget type enum, so it no longer makes sense to implement this into the lib. I will use your example code, thanks!

As for the Inner / InnerPtr - if it was implemented then I would be able to add my code on top of this library which would ideal.

Thanks again for the great work!
