### ISSUE TITLE
CameraFile::get_data is probably leaking memory

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#20]
From comment docs on `gp_file_get_data_and_size`:

```
 * For regular CameraFiles, the pointer to data that is returned is
 * still owned by libgphoto2 and its lifetime is the same as the #file.
 *
 * For filedescriptor or handler based CameraFile types, the returned
 * data pointer is owned by the caller and needs to be free()d to avoid
 * memory leaks.
 *
 **/
```

**Comment by maxicarlos08** [comment]
I'm not sure if I understand this correctly. Would calling `libc::free(file data)` after the data has been put in a slice if the file is a filedescriptor, be enough?

**Comment by RReverser** [comment]
Yeah, that's my understanding too.

**Comment by maxicarlos08** [comment]
> still owned by libgphoto2 and its lifetime is the same as the #file

Wouldn't that mean the the returned file data is only valid as long as the CameraFile is alive?

**Comment by RReverser** [comment]
Yes, but you already copied it into the Box anyway.

**Comment by maxicarlos08** [comment]
Ah, I missed that
