### ISSUE TITLE
Hook up gp_log_add_func

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#28]
As a follow-up to #26, it's also worth hooking up the global logging function `gp_log_add_func` to the `log` crate too as it provides even more info.

**Comment by RReverser** [comment]
Actually, I see now that `gp_context_error` automatically calls `gp_log(GP_LOG_ERROR, ...)`, so `gp_log_add_func` is strictly broader, and, once added, the bindings from #26 can be removed.

**Comment by maxicarlos08** [comment]
Added as a cargo feature

**Comment by maxicarlos08** [comment]
Added as a cargo feature
