### ISSUE TITLE
Relicensing to LGPL

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#3]
libgphoto2 itself is licensed under LGPL-v2.1, which allows it to be used in many more contexts than GPL does.

Currently, the Rust wrapper is licensed under GPL-v3.0, which makes it unnecessarily more restrictive than the library itself.

Would it be possible to change license of the Rust wrapper to make it at least as permissive as the underlying library?

**Comment by maxicarlos08** [comment]
Ok, I have no experience with that licensing stuff. What you said makes sense.

I will change the license to LGPL-v2.1 on the next release (coming in an hour or so with windows support :+1: )
