### ISSUE TITLE
Consistent filesystem access?

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#33]
All of the `gp_camera_file_*` and `gp_camera_folder_*` functions are thin wrappers around the corresponding `gp_filesystem_get_*`.

I wonder if it would be better to avoid exposing those bindings on `Camera` and instead focus only on `CameraFS`.

While libgphoto2 itself has to maintain both at least for backward compatibility, there's no need to bind both categories for us. On the other hand, exposing a single, consistent, interface for all file manipulation could be better from ergonomics perspective.

WDYT?

**Comment by RReverser** [comment]
For example, right now there are no bindings for `gp_filesystem_get_file` in `CameraFS`, but there are `CameraFilePath::{download, get_in_memory}`.

Since the former is strictly more general (supports any files, not just those captured via `capture_image`), replacing the latter with `CameraFS` bindings would cover both use-cases.

**Comment by maxicarlos08** [comment]
Yes but from where do I get a `CameraFilesystem`? and is it meant to be used in for this? the docs say it should be only used by camera drivers

**Comment by RReverser** [comment]
> Yes but from where do I get a `CameraFilesystem`?

What do you mean? You already have bindings for it in `filesys.rs` 🤔

> the docs say it should be only used by camera drivers

Oh, I haven't seen those. Are you saying `CameraFS` bindings shouldn't exist at all?

**Comment by maxicarlos08** [comment]
> What do you mean? You already have bindings for it in filesys.rs thinking

Actually no, `CameraFS` just has a reference and calls the `gp_camera_file_*` and `gp_camera_folder_*` functions. (I agree that this naming is confusing)

> Oh, I haven't seen those. Are you saying CameraFS bindings shouldn't exist at all?

Our CameraFS is ok since it used the filesystem functions on the camera, just the `CameraFilesystem` [should not be used](https://github.com/gphoto/libgphoto2/blob/master/gphoto2/gphoto2-camera.h#L327)

**Comment by RReverser** [comment]
> Actually no, `CameraFS` just has a reference and calls the `gp_camera_file_*` and `gp_camera_folder_*` functions. (I agree that this naming is confusing)
> 
> >

Ah sorry I got confused, I thought it's using `gp_filesystem_*` functions for some reason.

> Our CameraFS is ok since it used the filesystem functions on the camera, just the `CameraFilesystem` [should not be used](https://github.com/gphoto/libgphoto2/blob/master/gphoto2/gphoto2-camera.h?rgh-link-date=2022-09-27T06%3A03%3A52Z#L327)

I guess you meant to link to https://github.com/gphoto/libgphoto2/blob/8b462f8c835b9d3ab0cee4117e0b0458dac00445/gphoto2/gphoto2-filesys.h#L227-L233 instead, since that comment is about `Camera` fields.

---

Anyway, okay, yeah, I got confused about specific APIs :) In that case my suggestion about unifying entry points for filesystem access still stands, but it's just about moving `download` & `get_in_memory` into `CameraFS` instead of `CameraFilePath`.

**Comment by RReverser** [comment]
Reopening as per https://github.com/maxicarlos08/gphoto2-rs/pull/35#discussion_r981731033.
