### ISSUE TITLE
libgphoto2 is actually not thread-safe at all :(

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#43]
Continuation of the multithreading shenanigans, and I found out that libgphoto2 is actually non-reentrant - not safe to use from multiple threads even if you create separate Contexts. We'll need to wrap around this unsafety somehow (see my suggestion at the end of the quote).

<details>

> Now that I'm looking a bit deeper, I'm actually not sure that libgphoto2 is thread-safe at all, so fixing ltdl codepaths won't help much... There seems to be a lot of global mutable variables throughout the codebase, which are not protected by mutexes or atomics, and as such are inherently prone to corruption via race conditions.
> 
> So even if one takes care and creates separate gphoto2 contexts per-thread, all those internal data structures can be still corrupted by racing calls.
> 
> I guess the only safe way to use gphoto2 in multithreaded environment is to actually pin it to a single thread and make sure all work, for all devices, is done there. (at least until it's refactored in some future to avoid global variables, or to have mutex around all of them)
> 
> _Originally posted by @RReverser in https://github.com/gphoto/libgphoto2/issues/848#issuecomment-1289591222_
> 

 </details>

**Comment by maxicarlos08** [comment]
Oof, that sound bad. (at this point, why not rewrite libgphoto2 entirely in rust? /s).

If I understand this correctly, you suggested to start another thread in this library and to execute every libgphoto2 call on that thread and send the result back?  I think this would add some unnecessary overhead for single-threaded projects, but it unfortunately seems to be the only way to make it safe right now :( 

To prevent people from running into this issue, I will add a warning to the README for now.

**Comment by RReverser** [comment]
> If I understand this correctly, you suggested to start another thread in this library and to execute every libgphoto2 call on that thread and send the result back?

Yup.

> I think this would add some unnecessary overhead for single-threaded projects, but it unfortunately seems to be the only way to make it safe right now :(

I don't think it's going to be too bad. Don't forget that we're talking about a library that talks to external devices over USB and does some very expensive stuff. It's very hard to add any noticeable overhead on top of that :)

**Comment by RReverser** [comment]
Besides, moving tasks to another thread allows to unblock the main thread and thus make even single-threaded apps faster. libgphoto2 internally does quite a lot of `sleep` calls to wait for some external data, and right now all those sleeps would block e.g. UI interactivity if libgphoto2 and UI renderer are on the same thread.

By splitting them up, we can return every long task as a `Future` instead, and let apps handle long-running tasks gracefully (e.g. integrate gphoto2's task cancellation, better integrate per-task progress, etc.).

**Comment by maxicarlos08** [comment]
Hmm, that would mean that this crate can't be used without an async runtime, right?

The idea sounds good, but I still think that it isn't the best for every project.

In my gcam project I have solved this issue by having one "camera" thread where all gphoto operations run (sent by the UI thread as a closure and a result can be sent backis). AFAIK futures wouldn't help much here since they don't seem to be integrated/usable in egui + I would have to add an async runtime (which tend to be quite large).

Maybe we could an another module (maybe `gphoto2::async`) and make it available with a feature flag?

**Comment by RReverser** [comment]
> In my gcam project I have solved this issue by having one "camera" thread where all gphoto operations run

Right, that's what we'll have to do in gphoto2-rs either way, so that every user doesn't have to replicate the same logic of sending tasks to threads.

> I would have to add an async runtime (which tend to be quite large).

For something like this even [futures_lite](https://docs.rs/futures-lite/latest/futures_lite/) would be enough, if you want to just do `block_on` - that would bring back the synchronous behaviour for those who are okay to block for multiple seconds.

**Comment by maxicarlos08** [comment]
That sounds good!

Just one more thing: Is it "safe" to Send libgphoto2 pointers between threads (but functions can only be called on one thread)? Eg. The camera widget types has an internal raw libgphoto2 pointer which makes it `!Send`, but this widget must be sent to the "camera" thread for setting or sent to the parent for getting.

Would it be OK if I just create a wrapper `ThreadResponse<T>` type which unsafely implements `Send`?

**Comment by RReverser** [comment]
> Just one more thing: Is it "safe" to Send libgphoto2 pointers between threads (but functions can only be called on one thread)?

Well sending pointers themselves is no-op, but you need to be very careful to be sure you don't access it from any other thread. I can recommend https://docs.rs/send_wrapper/latest/send_wrapper/ - I used it to wrap gphoto2 types for now to 1) make them Send in my app and 2) to make sure I only use them always from the same thread. You can use it internally in gphoto2-rs to ensure the same.

**Comment by RReverser** [comment]
If done carefully, we can probably even make it possible to access e.g. widget properties without sending them to background task; doing `.id().wait()`, `.name().wait()` etc. would be pretty unpleasant, but then, I think those functions don't access any static variables anyway.

**Comment by RReverser** [comment]
I see you added

```
Currently, libgphoto2 does not seem to be thread safe at all.
This means that you cannot create Context’s on separate threads without risking to create internal race conditions.
```

to the docs. But now that you implemented a background thread, it should be fine to create Contexts anywhere, right, since gphoto2-rs will coalesce everything to the same thread internally anyway?

**Comment by maxicarlos08** [comment]
Whoops, totally forgot to remove that. Thanks!
