### ISSUE TITLE
Problem with tauri

### ISSUE THREAD

**Issue by orangelckc** [maxicarlos08/gphoto2-rs#46]
I try to use this wrapper on tauri, but face the following issue, is this a problem with gphoto2 or tauri?
![image](https://user-images.githubusercontent.com/48410934/206317351-d23e8b11-16b0-49e0-9621-6bb742fb1908.png)

**Comment by maxicarlos08** [comment]
Hello @orangelckc, sorry for the delayed response (I was on holidays without my laptop) :/

> **Warning**: I have no Tauri experience

I assume the error happens in a tauri command (tip: adding a minimal reproduction or code snippet can help debug these problems easier :wink:), however the return type of a command is expected to implement [Serialize](https://docs.rs/serde/latest/serde/trait.Serialize.html).

None of the structs in this library implement that.

There are 2 solutions to this problem:
 - If your are just going to to return results with `gphoto2::Error` as the error, but no other `gphoto2` in `Ok(..)` you could create a custom error type ([thiserror](https://docs.rs/thiserror) makes this very easy) which additionally implements `Serialize` and `From<gphoto2::Error>`
 - If you also return other types from this library, I could add `Serialize` implementations for them behind the `serde` feature flag..

You tell me which of these your prefer :)

**Comment by maxicarlos08** [comment]
I think i'll go with number 2 since it seems to be a better long term solution
