### ISSUE TITLE
Example code in README.md does not work

### ISSUE THREAD

**Issue by jensanjo** [maxicarlos08/gphoto2-rs#47]
The example code to take a picture in the `README.md` gives an error message: `Error: Path not absolute`.
The file and folder arguments in `camera_fs.download_to` are reversed.
```rust
camera_fs.download_to(&file_path.name(), &file_path.folder(), Path::new(&file_path.name().to_string())).wait()?;
```
Should be:
```rust
camera_fs.download_to(&file.folder(), &file.name(), Path::new(&file.name().to_string())).wait()?;
```
The code in the `examples/capture.rs` runs fine.

**Comment by maxicarlos08** [comment]
Thanks for noticing! (It was probably not updated in this PR #38).
