### ISSUE TITLE
Mixed Widget types in error message.

### ISSUE THREAD

**Issue by alex5250** [maxicarlos08/gphoto2-rs#58]
I tried to use lib, however i spent long period of time on this error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified error [Expected GroupWidget but got RadioWidget { id: 2, name: "shutterspeed", label: "Shutter Speed", readonly: false, choices: [_; 53], choice: "1/250" }]'`

however changing the type to GroupWidget:
`let mut shutterspeed = camera.config_key::<gphoto2::widget::GroupWidget>("shutterspeed").wait().unwrap();
`
is not helping, however if i will change it to:
`
    let mut shutterspeed = camera.config_key::<gphoto2::widget::RadioWidget>("shutterspeed").wait().unwrap();`
 
Error is gone. It seems that in error message GroupWidget and RadioWidget are mixed. 
 Here is simple example that will help you to  figure out:
   
   
```
use gphoto2::{Camera, Context, Result};
use gphoto2::widget::{RadioWidget, Widget};

fn get_iso(camera: Camera) {
    let mut shutterspeed = camera
        .config_key::<gphoto2::widget::GroupWidget>("shutterspeed")
        .wait()
        .unwrap();
    let mut camera_model = camera
        .config_key::<gphoto2::widget::TextWidget>("cameramodel")
        .wait()
        .unwrap();
}

fn main() -> Result<()> {
    env_logger::init();
    let camera = Context::new()?.autodetect_camera().wait()?;
    get_iso(camera);
    Ok(())
}

```

**Comment by alex5250** [comment]
result by now:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unspecified error [Got GroupWidget but expected RadioWidget { id: 2, name: "shutterspeed", label: "Shutter Speed", readonly: false, choices: [_; 53], choice: "1/250" }]'
```

**Comment by maxicarlos08** [comment]
I don't think this error message makes it any more clear, your code is clearly expecting to get a `GroupWidget`, but is getting a `RadioWidget`.

The new message incorrectly suggests that the code was expecting the widget returned from the camera but got the one expected in code.

**Comment by alex5250** [comment]
Well, probably i am not clear enought ,but it works with RadioWidget not GroupWidget.
Not oposite!
