### ISSUE TITLE
Context & the rest shouldn't have a lifetime

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#6]
Right now, `Context` creates an unbounded lifetime (see [Unbounded Lifetimes](https://doc.rust-lang.org/nomicon/unbounded-lifetimes.html#unbounded-lifetimes) tied to whatever scope it was created in via `Context::new`. This is not very useful and doesn't provide any extra guarantees, since the pointers returned from libgphoto2 are heap-allocated anyway. As such, the lifetime from `Context` and most of other data structures that inherit the same lifetime, can be safely removed.

@maxicarlos08 do you want to take this one?

**Comment by maxicarlos08** [comment]
`Camera` has a reference to a `Context` since it is required for most camera operations, its ok to keep the `Camear` lifetime for the `Context` right?

**Comment by RReverser** [comment]
> `Camera` has a reference to a `Context` since it is required for most camera operations, its ok to keep the `Camear` lifetime for the `Context` right?

In principle, yes, but personally I'd instead use `gp_camera_ref` + `gp_camera_unref` to avoid lifetime and instead use gphoto's reference counting.

**Comment by maxicarlos08** [comment]
This is actually great! Now you can initialize the camera without having to keep the context variable:

```rust
use gphoto2::{Result, Context};

fn main() -> Result<()> {
    let camera = Context::new()?.autodetect_camera()?; // This now compiles 🎉

    Ok(())
}

```

Thx for the reminder that gphoto had its own referencing counting!

**Comment by maxicarlos08** [comment]
v1.3.4 Now includes (almost, except for CameraFS and WidgetIterator) no more lifetimes

**Comment by RReverser** [comment]
> v1.3.4 Now includes (almost, except for CameraFS and WidgetIterator) no more lifetimes

I suspect technically it should've been 1.4.0 as it's an API breaking change, but otherwise great!
