### ISSUE TITLE
Missing Feature: Liveview

### ISSUE THREAD

**Issue by p0kR** [maxicarlos08/gphoto2-rs#65]
The gphoto2 feature live view might be missing in this rust binding.
With this feature of gphoto2 you can capture a live preview video stream from a supported camera.
To approach feature completeness of this binding with the original gphoto2, I think this feature should be added, if possible.

As there is no std video stream API in rust I know of, my suggestion would be to provide some interface that could, for example, be connected to the [official rust binding for gstreamer](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs) (maybe as a video-source  for gst-pipelines) or other popular media framework.

**Comment by benterova** [comment]
Not a Rust aficionado but I poked around and this seems to be correct. Not urgent for the application I'm developing currently, but would like to know what the options are for future implementation/use.

**Comment by maxicarlos08** [comment]
Capturing live view is already possible via [`Camera::capture_preview()`](https://docs.rs/gphoto2/latest/gphoto2/camera/struct.Camera.html#method.capture_preview), `gphoto2` also internally uses this API for the `--capture-movie` flag (which is commonly used for obtaining a Live view video feeds)

**Comment by maxicarlos08** [comment]
Linking this as an example on how to use `capture_preview` to for capturing live views: https://github.com/gphoto/gphoto2/blob/d831dcbe5c73ad9c5956ae8e22d2ea65eedee485/gphoto2/actions.c#L1028
