### ISSUE TITLE
Windows help: runs great in mingw64 & ucrt64, gets Error loading a library output when trying to run outside of msys2 env.

### ISSUE THREAD

**Issue by benterova** [maxicarlos08/gphoto2-rs#66]
Hey there, pretty stumped and don't know how else to try to move forward.

I have a basic application that uses these bindings and it successfully compiles and runs when executed from within mingw64 and ucrt64, however running `ntldd -R`and copying over the dll's for my application (just `libgphoto2-6.dll`, `libgphoto2_port-12.dll` and their non-system dependencies) to the `target/debug` directory where the executable sits, and running through `cmd`, I get the error: `Error loading a library`. It is not more descriptive than that and I'm not sure how to get a more verbose output. I've tried increased logging, backtraces, etc, Windows & Visual Studio debugging tools to no avail.

I believe it has to do with libgphoto2 as it happens when trying to initialize the camera handler in my application, but i'd love to have some additional input as to what to try next. 

The full list of DLL's I have in the same directory as the compiled executable:
```
libexif-12.dll
libgphoto2_port-12.dll
libgphoto2-6.dll
libintl-8.dll
libiconv-2.dll
libsystre-0.dll
libtre-5.dll
libwinpthread-1.dll
```
Happy to provide any other information that might be useful to help get to the bottom of this.

**Comment by maxicarlos08** [comment]
Unfortunately I don't have a windows system to further debug this, perhaps @RReverser knows more?

**Comment by RReverser** [comment]
Libgphoto2 dynamically enumerate and loads extra DLLs for plugins for cameras and ports. Those are missing in your list because `dlopen` calls they can't be seen by `ntldd`.

**Comment by benterova** [comment]
> Libgphoto2 dynamically enumerate and loads extra DLLs for plugins for cameras and ports. Those are missing in your list because `dlopen` calls can't be seen by `ntldd`.

That makes sense, I'm assuming this means the options for retrieving them are pretty limited, especially if planning on distributing. Thank you for helping me figure this out, wish the error was a bit more descriptive lol.

**Comment by RReverser** [comment]
> That makes sense, I'm assuming this means the options for retrieving them are pretty limited, especially if planning on distributing.

I think you should be fine if you just copy the entire subdirs containing those plugins. That's what e.g. Darktable does in their distributions:

![image](https://github.com/maxicarlos08/gphoto2-rs/assets/557590/f3aafa69-f9e4-4592-8c62-b1cfe2c9d1a1)

**Comment by benterova** [comment]
> > That makes sense, I'm assuming this means the options for retrieving them are pretty limited, especially if planning on distributing.
> 
> I think you should be fine if you just copy the entire subdirs containing those plugins. That's what e.g. Darktable does in their distributions:
> 
> ![image](https://private-user-images.githubusercontent.com/557590/293617204-f3aafa69-f9e4-4592-8c62-b1cfe2c9d1a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTQ4NTgsIm5iZiI6MTcwNDIxNDU1OCwicGF0aCI6Ii81NTc1OTAvMjkzNjE3MjA0LWYzYWFmYTY5LWY5ZTQtNDU5Mi04YzYyLWIxY2ZlMmM5ZDFhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNjU1NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzJlYTE5YjQxZmU4ODE2MTIzODBkZmI4YmQ5M2RmMjNlNzJhZmQ3MDZmNWMwNzVhMzMyODBlODJiNDcwNzNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lhTorGgy-IsmwR_QpaxnWz3iJD0G9Gl0e0TPdjEwaSs)

That's a very good idea, and likely the key I was missing. I'll give it a shot, thank you again for helping me figure this out!
