### ISSUE TITLE
LGPL license change

### ISSUE THREAD

**Issue by jemaw** [maxicarlos08/gphoto2-rs#69]
Since rust statically links in libraries it's quite difficult to conform to the requirements of LGPL. Essentially LGPL requires that one can swap out the LGPL parts of the software, for C this is easy and one can just provide a different dynamic `.so` library, for Rust it's not easily possible.

I'd suggest to either move to a permissive license like MIT or switch to something like MPLv2.
As examples:
- gstreamer is a LGPL C-library that use MIT/Apachev2 for the rust bindings: [license](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs#license)
- `librpm.rs` switched from LGPL to MPLv2: [github thread](https://github.com/rpm-software-management/librpm.rs/issues/21)

**Comment by maxicarlos08** [comment]
I don't plan on moving away from LGPL for this project.
