### ISSUE TITLE
String helpers have stack-use-after-return issues

### ISSUE THREAD

**Issue by RReverser** [maxicarlos08/gphoto2-rs#7]
After lifetime cleanup in #6, I've decided to take a look at other potential instances of unbounded lifetimes now that there's not much to look at.

I've noticed that string helpers have such unbounded lifetimes, but, unlike with heap pointers in #6, those can actually be harmful. For example:

```rust
pub fn camera_text_to_str<'a>(text: libgphoto2_sys::CameraText) -> Cow<'a, str> {
  unsafe { String::from_utf8_lossy(ffi::CStr::from_ptr(text.text.as_ptr()).to_bytes()) }
}
```

Here, `CameraText` contains on-stack array of chars. The helper takes a pointer to that stack array, passes via CStr & String conversions, and potentially gets a `Cow` back with that same pointer. Then, it claims that the returned pointer is valid and borrowed (from unbounded lifetime `'a`), and returns upwards, even though the actual data is no longer reachable once the function returns.

Same applies to usages of `chars_to_cow` whenever input pointer points to temporary on-stack data.

It's pretty hard to trigger this to show that strings might contain garbage once overridden by other stack data, but, as far as I can tell, it works only by accident.

Those unbounded lifetimes should be eliminated, and instead there should probably be a couple of helpers:

1) Takes `&'a [c_char]` and returns `Cow<'a, str>` - this would be most popular (there's lots of `[c_char; 123]` data in the codebase, including in `CameraText`) and safe as the lifetime would be clearly bound to the input.
2) Something like the current `chars_to_cow`, but marked `unsafe` so that it's clear it should be used only if you can pass explicit lifetime (e.g. strings returned from `Widget::name` etc. that are constructed from `*const c_char` that is valid as long as `Widget` itself).
3) `chars_to_string` for the rest of the cases, to immediately convert into `String` and not expect the input pointer to live after the function call.

**Comment by maxicarlos08** [comment]
Does this 7ba68a85cb0df9ca3d3bd62a124f020d41e28be3 fix the issue?

**Comment by maxicarlos08** [comment]
I think that's it
